export const colors = {
    tagsBackground: "#3e32e4",
    tagsText: "#ffffff",
    tagsBackgroundHoverActive: "#6e65f1",
    tagsTextHoverActive: "#ffffff",
    searchBackground: "#18191f",
    searchText: "#ffffff",
    searchPlaceHolder: "#575a77",
    playerBackground: "#333",
    titleColor: "#ffffff",
    timeColor: "#ffffff",
    progressSlider: "#eee",
    progressUsed: "#ffffff",
    progressLeft: "#eee",
    bufferLoaded: "#1f212b",
    volumeSlider: "#eeeeee",
    volumeUsed: "#ffffff",
    volumeLeft: "#151616",
    playlistBackground: "#18191f",
    playlistText: "#575a77",
    playlistBackgroundHoverActive: "#18191f",
    playlistTextHoverActive: "#ffffff",
  };